### ISSUE TITLE
Messages only going one way

### ISSUE THREAD

**Issue by Galapagon** [maxsupermanhd/FactoCord-3.0#1]
Maxsupermanhd,

First, let me say how grateful I am that you picked up this abandoned project and continued work on it. I followed the instructions as best as possible, and I got it working... kinda.

The bot let me know that the server started, and when I send a message from discord, it shows up in game! it does not however, work the other way (in game chat does not get sent to discord). Do you have any idea where I might troubleshooting to resolve this problem?

**Comment by maxsupermanhd** [comment]
Lemme look at your config and discord. Can you invite me on server if its not private?
And doublecheck perms on discord bot and channel maybe it just cant read it.
And also if you can see messages in server console like `xxxx/xx/xx xx:xx:xx ["Name"] message` and it dont sending this into discord you need to check channel ids

**Comment by Galapagon** [comment]
Actually, it's working now, I think rebuilding one of the go libraries might have fixed it? I'm not sure.

I still can't send commands from discord though. I tried $restart and it just pulls help back up. Am I missing something else?

**Comment by Galapagon** [comment]
Also, I don't see a server console. I have a mixed install... I had to pull things from the original factocord... not sure if I was supposed to do that.

**Comment by Galapagon** [comment]
I feel like I'm missing a config file to set a console channel?
