### ISSUE TITLE
Afk disconnect message didn't send

### ISSUE THREAD

**Issue by Galapagon** [maxsupermanhd/FactoCord-3.0#16]
console shows 
0000-00-00 00:00:00 [DISCORD] **Player** left.
But message never came through on discord, even after bumping the chat, which did go through to factorio properly

**Comment by maxsupermanhd** [comment]
Is this message somehow different from chat/join messages?

**Comment by Galapagon** [comment]
I'll test tomorrow Max and send you more info

**Comment by Galapagon** [comment]
10692.249 Info ServerMultiplayerManager.cpp:1037: Disconnect notification for peer (2)
10692.271 Info ServerSynchronizer.cpp:618: nextHeartbeatSequenceNumber(276605) removing peer(2).

**Comment by maxsupermanhd** [comment]
This is expected from Factorio. 

Custom scenario enabled: if there is no [DISCORD] message when scenario enabled then It's scenario problem

Custom scenario disabled: if there is no [LEFT] message (Factorio don't sends this one in some cases I believe...) then no will be sent to discord.

**Comment by Galapagon** [comment]
ah dang I forgot to add it in the new map

**Comment by maxsupermanhd** [comment]
Also if custom scenario enabled, bot will read only [DISCORD] and [DISCORD-EMBED] messages. (Yeah you can send embeds from game console)

**Comment by Galapagon** [comment]
2020-06-02 12:45:57 [CHAT] 
0000-00-00 00:00:00 [DISCORD] <junhinhow> srry for that... my bad..
6793.806 Info AppManager.cpp:297: Saving to _autosave12 (blocking).
6794.901 Info AppManagerStates.cpp:1844: Saving finished
6924.782 Info ServerMultiplayerManager.cpp:1037: Disconnect notification for peer (1)
6924.784 Info ServerSynchronizer.cpp:618: nextHeartbeatSequenceNumber(176163) removing peer(1).
0000-00-00 00:00:00 [DISCORD] **Galapagon** left.
2020-06-02 12:55:42 [CHAT]

While staring at the AFK screen

[12:45 PM] 
BOT
 Don't tread on: (player chat)
[12:55 PM] 
BOT
 Don't tread on: (player chat)

**Comment by maxsupermanhd** [comment]
Resolved in Discord.
