### ISSUE TITLE
Not able to send console commands

### ISSUE THREAD

**Issue by Galapagon** [maxsupermanhd/FactoCord-3.0#3]
When I try commands like $stop from discord, it just pulls up the list of available commands again.
 I set my ID as admin in the env file.
I also tried changing the invoke to $$ and it still only responded with the list of commands

**Comment by maxsupermanhd** [comment]
Is this resolved?

**Comment by Galapagon** [comment]
Seems to still be a problem, here's a invite link good for one use https://discord.gg/NNKYgr

**Comment by maxsupermanhd** [comment]
Youknow im superfast as light so pls join me on [discord.gg/SUJRG47](discord) (MaX)

**Comment by Galapagon** [comment]
opened new issue https://github.com/maxsupermanhd/FactoCord-3.0/issues/5 with what I believe is causing the bug. Was able to get console channel by adding FactorioConsoleChatID = "ID HERE" to my .env file
