### ISSUE TITLE
[BUG] Restart command existing

### ISSUE THREAD

**Issue by Galapagon** [maxsupermanhd/FactoCord-3.0#32]
**BUG-FILTER-CHECKLIST.** Anyone who opens up a bug report must fill these checkboxes (add an "x" to `[ ]` to be like `[x]`) to assume that he acknowledged that he red README.md and followed checklist below.
- [ x] Bot have rights to write, read and send embeds to desired channel.
- [x ] Executable not receiving SIGTERM, SIGKILL or other terminating signals during work.
- [x ] Scenario/mods are working correctly and not crashing game.
- [x ] I'm using FactoCord-compatible scenario that writes up all desired text to console with `[DISCORD]` tag.
- [x ] I have direct access to shell that runs FactoCord. (via tmux, screen or whatever that pipes `stdin` **and** `stderr` to output)

**Describe the bug**
Messages are inconsistant and in some instances sending too many messages.

**To Reproduce**
$restart sends Four messages, $stop sends a different message

**Expected behavior**
Restart should probably only send two messages.
:Recycle: Saved server, now restarting!
Definately NOT :octagonal_sign: The server has stopped!

Server restarted successfully! -OR- white_check_mark Galapagon.freemyip.com:34198 (June Base) has started!
Restart message seems to send before server is ready for clients to connect though.

$stop is also sending a 3rd different message at this time
Server saved and shutting down; Cya!
Should probably be :octagonal_sign: The server has stopped! since that is what is in .env

**My instance information**
- FactoCord version: 3.1
- Factorio version: 18.33

**Comment by TechnoStrife** [comment]
`restart` is bugged at the moment as it doesn't wait for factorio to exit and starts a new instance that refuses to run because previous one hasn't exited.
I will probably just remove those not-configurable messages because they're about what the bot is doing rather than what factorio is doing

**Comment by Galapagon** [comment]
I just ran restart on my server and it was able to restart properly
could be because the server was still in the initial waiting state
