### ISSUE TITLE
Server saved messages causing spam

### ISSUE THREAD

**Issue by Galapagon** [maxsupermanhd/FactoCord-3.0#37]
BUG-FILTER-CHECKLIST. Anyone who opens up a bug report must fill these checkboxes (add an "x" to [ ] to be like [x]) to assume that he acknowledged that he red README.md and followed checklist below.

    [ x] Bot have rights to write, read and send embeds to desired channel.
    [x ] Executable not receiving SIGTERM, SIGKILL or other terminating signals during work.
    [x ] Scenario/mods are working correctly and not crashing game.
    [x ] I'm using FactoCord-compatible scenario that writes up all desired text to console with [DISCORD] tag.
    [x ] I have direct access to shell that runs FactoCord. (via tmux, screen or whatever that pipes stdin and stderr to output)

Describe the bug
Server saved is flooding chat
Also, server saved message appears to be hard coded not linked to .env

To Reproduce
Server is running in no pause mode, so game is constantly saving when no players are present. These save messages are ALL being relayed to discord and flooding the chat

Expected behavior
Some sort of message rate limit. Either only send one save message when no players are present, or limit frequency of messages sent when no players are present. May also want to make this adjustable in the user configs

My instance information

    FactoCord version: 3.1
    Factorio version: 18.34

**Comment by TechnoStrife** [comment]
Yeah, we know about it. 
It's fixed in server branch (v3.2.0) which is currently being tested.
You can test it too by installing pre-release v3.2.0
