### ISSUE TITLE
Go version

### ISSUE THREAD

**Issue by szentigrad3** [maxsupermanhd/FactoCord-3.0#38]
noidea@exothermic:~/FactoCord-3$ sudo go build
# _/home/noidea/FactoCord-3
./main.go:51:80: Factorio.ProcessState.ExitCode undefined (type *os.ProcessState has no field or method ExitCode)

**Comment by maxsupermanhd** [comment]
1. You need to learn markdown syntax
2. You don't need sudo on `go build` command, it will be fine with regular permissions.
3. You need to update your go version, readme is wrong. Don't ask how to do it, you have google for that.

**Comment by szentigrad3** [comment]
what version do i need?

**Comment by TechnoStrife** [comment]
1.12+

**Comment by maxsupermanhd** [comment]
1.14 will do the thing.

**Comment by szentigrad3** [comment]
got 1.14 installed now getting this error > # _/home/noidea/FactoCord-3/discord
discord/log.go:97:12: message.TTS undefined (type *discordgo.MessageSend has no field or method TTS, but does have Tts)

**Comment by TechnoStrife** [comment]
install discordgo 0.21+

**Comment by TechnoStrife** [comment]
you can install prebuilt binary from releases page

**Comment by szentigrad3** [comment]
i did run go get github.com/bwmarrin/discordgo

**Comment by TechnoStrife** [comment]
for some reason it installed previous version

**Comment by szentigrad3** [comment]
2020-07-09 20:33:24.558521902 +1000 AEST m=+0.000602856, _/home/TechoStrife/FactoCord-3.0/support.Critical @ /home/TechoStrife/FactoCord-3.0/support/error.go:74
	An error occurred when parsing config.json: invalid character ']' looking for beginning of value

**Comment by TechnoStrife** [comment]
https://github.com/maxsupermanhd/FactoCord-3.0/blob/server/INSTALL.md#step-0
The last sentence.

**Comment by TechnoStrife** [comment]
There's an explicit message in the console: "Note that json5 may have several bugs, such as comment before ] or }"

**Comment by szentigrad3** [comment]
i have done that same error

Welcome to FactoCord-3.0!
Note that json5 may have several bugs, such as comment before ] or }
An error occurred when parsing config.json
You can post your issue on https://github.com/maxsupermanhd/FactoCord-3.0/issues

**Comment by TechnoStrife** [comment]
??

**Comment by szentigrad3** [comment]
[config.txt](https://github.com/maxsupermanhd/FactoCord-3.0/files/4896231/config.txt)

**Comment by TechnoStrife** [comment]
Don't you understand that you should remove comments before `]` or `}`?
Also admin_ids is an array for a reason.
Thx for the token btw
