### ISSUE TITLE
JSON5 config comments

### ISSUE THREAD

**Issue by ren-kun** [maxsupermanhd/FactoCord-3.0#39]
**BUG-FILTER-CHECKLIST.** Anyone who opens up a bug report must fill these checkboxes (add an "x" to `[ ]` to be like `[x]`) to assume that he acknowledged that he red README.md and followed checklist below.
- [X] Bot have rights to write, read and send embeds to desired channel.
- [X] Executable not receiving SIGTERM, SIGKILL or other terminating signals during work.
- [X] Scenario/mods are working correctly and not crashing game.
- [ ] I'm using FactoCord-compatible scenario that writes up all desired text to console with `[DISCORD]` tag.
OR (remove this and unnecessary line above or below)
- [ ] I'm using vanilla game and acknowledged about bugs and its workarounds.
- [X] I have direct access to shell that runs FactoCord. (via tmux, screen or whatever that pipes `stdin` **and** `stderr` to output)

**Describe the bug**
 Error log output:

> 2020-07-15 10:59:51.431573045 +0000 UTC m=+0.000378783, github.com/maxsupermanhd/FactoCord-3.0/support.Critical @ /home/fac/Facto3/FactoCord-3.0/support/error.go:74
> 	An error occurred when parsing config.json: invalid character ']' looking for beginning of value

**To Reproduce**
running version 3.2.0 when launching the ./FactoCord-3.0 command outputs:

> Note that json5 may have several bugs, such as comment before ] or }
> An error occurred when parsing config.json

**Expected behavior**
 It should launch, I don't see missin '[' or ']'
https://jsonformatter.org/json5-validator doesn't report anything bad either

**My instance information**
- OS: Ubuntu 18.04LTS
- golang version:  go1.14.5 linux/amd64
- FactoCord version: #33 
- Factorio version: 0.17.79
- Server config: uploaded config.json
[factorio.txt](https://github.com/maxsupermanhd/FactoCord-3.0/files/4924769/factorio.txt)

**Comment by maxsupermanhd** [comment]
> Note that json5 may have several bugs, such as comment before ]

Please remove commented line in admin ids array, this might cause error.

**Comment by ren-kun** [comment]
Sorry, sent the wrong file.  I have admin_ids array populated

**Comment by maxsupermanhd** [comment]
Try to remove **every** comment in file, that should clear up...

**Comment by maxsupermanhd** [comment]
Any progress? (btw json5 config file is pretty buggy, this is not FactoCord issue)
