### ISSUE TITLE
Commands not linked properly

### ISSUE THREAD

**Issue by Galapagon** [maxsupermanhd/FactoCord-3.0#42]
Commands such as _stop_ and _restart_ defined separately in **command_roles** but are all tied to _$server command_ in prod. Therefore, Command eg: _$Server restart_ can not be delegated without making a player full admin and/or full control over _$server_ command.

**Comment by TechnoStrife** [comment]
I forgot to delete them

**Comment by TechnoStrife** [comment]
I could've just typed `"server": "123456789"` and it would've worked
