### ISSUE TITLE
[BUG] server crashes on mod update

### ISSUE THREAD

**Issue by Galapagon** [maxsupermanhd/FactoCord-3.0#43]
**BUG-FILTER-CHECKLIST.** Anyone who opens up a bug report must fill these checkboxes (add an "x" to `[ ]` to be like `[x]`) to assume that he acknowledged that he red README.md and followed checklist below.
- [x] Bot have rights to write, read and send embeds to desired channel.
- [x] Executable not receiving SIGTERM, SIGKILL or other terminating signals during work.
- [x] Scenario/mods are working correctly and not crashing game.

- [x] I have direct access to shell that runs FactoCord. (via tmux, screen or whatever that pipes `stdin` **and** `stderr` to output)

**Describe the bug**
goroutine 6626 [running]:

github.com/maxsupermanhd/FactoCord-3.0/commands/admin.checkDependencies(0xc0004cc080, 0x1,
0x1, 0xc0002fa080, 0x1, 0xc0003ea270)

/factorio/FactoCord-3.0/commands/admin/mod.go:653 +0x1f1d

github.com/maxsupermanhd/FactoCord-3.0/commands/admin.modsUpdate(0xc0000ba480,
0xc00028a180, 0xc000167908, 0x6, 0x1)

/factorio/FactoCord-3.0/commands/admin/mod.go:439 +0x520

github.com/maxsupermanhd/FactoCord-3.0/commands/admin.ModCommand(0xc0000ba480,
0xc0001c8794, 0x6)

/factorio/FactoCord-3.0/commands/admin/mod.go:256 +0x831

github.com/maxsupermanhd/FactoCord-3.0/commands.RunCommand(0xc0001c8710, 0xa,
0xc0000ba480, 0xc0000ce6e0)

/factorio/FactoCord-3.0/commands/commands.go:271 +0x3ea

github.com/maxsupermanhd/FactoCord-3.0/discord.messageCreate(0xc0000ba480, 0xc0004cc050)

/factorio/FactoCord-3.0/discord/chat.go:75 +0xed7

github.com/bwmarrin/discordgo.messageCreateEventHandler.Handle(0x7f58f0, 0xc0000ba480,
0x76b780, 0xc0004cc050)

/go/pkg/mod/github.com/bwmarrin/discordgo@v0.21.1/eventhandlers.go:497 +0x57
created by github.com/bwmarrin/discordgo.(*Session).handle

/go/pkg/mod/github.com/bwmarrin/discordgo@v0.21.1/event.go:171 +0x111

**To Reproduce**
$mod update

**Expected behavior**
mods would update

**My instance information**
- OS: ubuntu 20
- golang version: 1.13.8`
 - FactoCord version: v3.2.13-alpha
- Factorio Server version: 1.1.8

**Comment by TechnoStrife** [comment]
Please send me the list of mods

**Comment by Galapagon** [comment]
52 total mods (41 enabled, 11 disabled)
Enabled:
    base
    angelsaddons-storage
    angelsbioprocessing
    angelsexploration
    angelsindustries
    angelsinfiniteores
    angelspetrochem
    angelsrefining
    angelssmelting
    bobassembly
    bobclasses
    bobelectronics
    bobenemies
    bobequipment
    bobgreenhouse
    bobinserters
    boblibrary
    boblogistics
    bobmining
    bobmodules
    bobores
    bobplates
    bobpower
    bobrevamp
    bobtech
    bobvehicleequipment
    bobwarfare
    Bottleneck
    copy-recipe-to-chest
    CredoTimeLapseModByGalapagon
    DiscoScience
    even-distribution
    flib
    FNEI
    helmod
    Inventory Sensor
    LogisticTrainNetwork
    LTN_Content_Reader
    SchallSatelliteController
    Squeak Through
    Todo-List

Disabled:
    deadlock-beltboxes-loaders
    DeadlockCrating
    ElectricTrain
    ev-refining
    Factorissimo2
    informatron
    MaxRateCalculator
    RenaiTransportation
    RibbonMaze018
    robot_attrition
    WhistleStopFactories
