### ISSUE TITLE
Slash commands

### ISSUE THREAD

**Issue by ComputerComa** [maxsupermanhd/FactoCord-3.0#44]
Will the command structure be moved to slash commands? 
I really like the look and feel of this project, but I would really like to see the ability to use slash commands.

**Comment by TechnoStrife** [comment]
Probably, when I get more free time

**Comment by ComputerComa** [comment]
Cool! I would offer to help, but I'm not very familiar with lua or go.

**Comment by TechnoStrife** [comment]
@ComputerComa slash commands are ready.

Before I make a release you can test them in the test server: https://discord.gg/uNhtRH8

**Comment by ComputerComa** [comment]
OOh. Thanks! And alright!

**Comment by TechnoStrife** [comment]
Test build ready. It can be found in releases

**Comment by ComputerComa** [comment]
Hey sorry, I took a little break from Factorio but I definitely will be taking a look again at this soon!

**Comment by ComputerComa** [comment]
Are slash commands part of the stable releases now? I see that they show up in my server but i tried to use one and it just comes back with `Application did not respond`
![image](https://github.com/maxsupermanhd/FactoCord-3.0/assets/68386555/0d4a3457-c5d0-4ab3-bb3e-0a9a851f3431)

**Comment by maxsupermanhd** [comment]
The `Application did not respond` error is happening when bot did not acknowledged or responded to the command within 5 seconds (iirc). The only 2 ways that "no response" can be observed is at first you launch bot with slash command support and then rolled back to a version that does not know about them (old registration of command is being used) and when bot actually did not respond and likely crashed or encountered some sort of error that made it not respond back (should be something written in the logs on the server/tty).

Unfortunately I am long gone from Factorio (and suppose so is TechnoStrife) so I don't immediately know an answer to your question nor do I even remember how FactoCord implemented slash commands and in what branch it is.

**Comment by TechnoStrife** [comment]
They were working fine when I published a [test build](https://github.com/maxsupermanhd/FactoCord-3.0/releases/tag/v3.3.1) with slash commands.
Can't guarantee that now. Also there isn't exactly a high demand for them, so...

**Comment by ComputerComa** [comment]
Ok Fair enough.
