### ISSUE TITLE
[BUG] Discord Guild

### ISSUE THREAD

**Issue by szentigrad3** [maxsupermanhd/FactoCord-3.0#45]
2022-04-05 04:04:15.952515718 +0000 UTC m=+3.054228293, github.com/maxsupermanhd/FactoCord-3.0/support.Critical @ /home/runner/work/FactoCord-3.0/FactoCord-3.0/support/error.go:74
	An error occurred when attempting to read the Discord Guild: HTTP 403 Forbidden, {"message": "Missing Access", "code": 50001}

it was all working and then i restarted the bot now its doing this

**Comment by TechnoStrife** [comment]
Please check that `"factorio_channel_id"` in the `config.json` is correct (or using the config command)

**Comment by maxsupermanhd** [comment]
Unable to reproduce or configuration issue. Will be reopened if more information will be available.
