### ISSUE TITLE
Auto close after mod crash

### ISSUE THREAD

**Issue by TwentyEighty** [maxsupermanhd/FactoCord-3.0#46]
If a mod crashes factorio, FactoCord3 just sits there until I kill it. Factorio has shut down, it's just FactoCord that's running. It would be better if factocord shut down when this happens. That way, I could use systemd or something like that to restart the process.

Is there already some way to do this?

**Comment by maxsupermanhd** [comment]
FactoCord monitors process, if it exits you can relaunch it with a command (`/server start`)
