### ISSUE TITLE
[Enhancement] - research notifications (not sure why it got marked as a bug.. sorry)

### ISSUE THREAD

**Issue by ComputerComa** [maxsupermanhd/FactoCord-3.0#50]
It would be really cool if there was an optional ability to send a message when research starts, completes, is cancelled etc...

I know the following events are emitted when research is [canceled](https://lua-api.factorio.com/latest/events.html#on_research_cancelled) , [started](https://lua-api.factorio.com/latest/events.html#on_research_started), and [finished](https://lua-api.factorio.com/latest/events.html#on_research_finished). 
So maybe it just takes adding a small script to output a message that Factocord Understands.. 
I'm just not smart enough to know what FactoCord is looking for to pass messages along.

**Comment by maxsupermanhd** [comment]
Have fun editing custom scenario. https://github.com/maxsupermanhd/FactoCord-3.0/blob/master/control.lua

**Comment by ComputerComa** [comment]
Oh! Totally missed that! Thx...
