### ISSUE TITLE
[BUG] Can't load newest version

### ISSUE THREAD

**Issue by szentigrad3** [maxsupermanhd/FactoCord-3.0#51]
i am running this within a docker apart of pterodactyl game panel and get this error, while if i use an older version of FactoCord it works fine

./FactoCord3: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./FactoCord3)
./FactoCord3: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./FactoCord3)

**Comment by TechnoStrife** [comment]
Please specify which version produces this error and which doesn't

**Comment by szentigrad3** [comment]
[v3.2.15](https://github.com/maxsupermanhd/FactoCord-3.0/releases/tag/v3.2.15) works
[v3.2.16](https://github.com/maxsupermanhd/FactoCord-3.0/releases/tag/v3.2.16) doesn't
[v3.2.17](https://github.com/maxsupermanhd/FactoCord-3.0/releases/tag/v3.2.17) doesn't

**Comment by TechnoStrife** [comment]
I tried to fix it. Please try running FactoCord3 from [this release](https://github.com/maxsupermanhd/FactoCord-3.0/releases/tag/v3.2.18-test)

**Comment by szentigrad3** [comment]
> I tried to fix it. Please try running FactoCord3 from [this release](https://github.com/maxsupermanhd/FactoCord-3.0/releases/tag/v3.2.18-test)

that works thanks alot
