### ISSUE TITLE
windows

### ISSUE THREAD

**Issue by szentigrad3** [maxsupermanhd/FactoCord-3.0#7]
any chance of a windows ports?

**Comment by maxsupermanhd** [comment]
Have you tried to build this on windows? Its **_theoretically_** possible but nobody tried.

**Comment by Galapagon** [comment]
I think this is the best information on the problem the original author was running into with Factorio windows https://github.com/FactoKit/FactoCord/issues/3#issuecomment-359981915 and my understanding is that factorio is still not a true console window like on Linux.
If you're running windows 10 I could help you set up a linux VM to use as a factorio server, but if you're running this on a dedicated system (or hypervisor) it'd be better to just build it on Lnix

**Comment by szentigrad3** [comment]
i got it working on windows, just the admin commands don't work also i can receive messages in discord but not send them and errors out > 2020-04-07 21:37:37.0385092 +1000 AEST m=+57.706849301: An error occurred when attempting to pass Discord chat to in-game
Details: write |1: The pipe is being closed.


2020/04/07 21:37:14 [Szentigrade] test
Opps, it looks like an error happened!
Please post your error.log on https://github.com/maxsupermanhd/FactoCord-3.0/issues

**Comment by maxsupermanhd** [comment]
As we said earlier this is kinda possible but Windows don't have sutch functions to handle pipes. This is Windows fault, so do not report it. Want to test this? Go install Linux or run VM.

**Comment by Galapagon** [comment]
Szentigrad3, you could also try downloading bash for windows, and running the linux version through that, no guarantee that it will work though. furthermore, bash for windows is basically a VM anyway

**Comment by TechnoStrife** [comment]
If you're talking about WSL then it's not a VM and it works pretty good. Docker on windows runs a VM though.

**Comment by szentigrad3** [comment]
i'm using windows server 2016 and WSL and Docker doesn't run on it

**Comment by maxsupermanhd** [comment]
Well, not an issue, refer to older threads.
